# NovaShop — SonarQube Statik Kod Analizi Yapılandırması
sonar.projectKey=novashop
sonar.projectName=NovaShop DevOps Store
sonar.projectVersion=0.1.0

# Kaynak ve Test Dizinleri
sonar.sources=src/ui/src/main/java
sonar.tests=src/ui/src/test/java
sonar.java.binaries=src/ui/target/classes

# Kod Kodlama ve Dışlama Kuralları
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.json,**/*.html,**/*.css,**/*.svg,**/*.sql
sonar.coverage.exclusions=**/*Application.java,**/config/**,**/model/**

# Kalite Eşikleri
sonar.qualitygate.wait=true
