# HTTP -> HTTPS Yönlendirmesi
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Sağlık kontrolü HTTP üzerinden de yanıt verir (Load Balancer dostu)
    location = /healthz {
        access_log off;
        default_type application/json;
        return 200 '{"status":"UP","tier":"3-tier-edge","protocol":"http"}\n';
    }

    # Diğer tüm istekleri güvenli HTTPS portuna zorla yönlendir (301)
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS Güvenli Web Katmanı
server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name _;

    # SSL / TLS Sertifikaları
    ssl_certificate /etc/ssl/novashop/novashop.crt;
    ssl_certificate_key /etc/ssl/novashop/novashop.key;

    # Güçlü TLS Protokol ve Şifreleme Ayarları
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    # Güvenlik Başlıkları
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    server_tokens off;

    # 1. Sağlık Kontrolü
    location = /healthz {
        access_log off;
        default_type application/json;
        return 200 '{"status":"UP","tier":"3-tier-edge","protocol":"https"}\n';
    }

    # 2. UI Storefront Reverse Proxy (127.0.0.1:8888)
    location / {
        proxy_pass http://127.0.0.1:8888;
        proxy_http_version 1.1;

        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_connect_timeout 5s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
